In [1]:
mytuple = ("James",23)
print(mytuple)

('James', 23)


In [7]:
fellowship = {
    'habbot_1':'James',
    'habbot_2':'Erick'
    }
x = fellowship['habbot_1']
print(x)

James


In [18]:
for x,y in fellowship.items():
    print(x,y)

habbot_1 James
habbot_2 Erick


In [20]:
import numpy as np
import random

student_data = np.random.choice(np.arange(1,100), size=50).reshape(10,5)
print(student_data)

student = [1,2,3,4,5,6,7,8,9,10]
studentdict = {}
courses = [1,2,3,4,5]
marks = {}

for x in range(len(student_data)):
    studentdict.update({student[x]: student_data[x]})  
print(studentdict)

for i in range(student_data.shape[1]):
    print(f"Course {courses[i]}: {student_data[:, i]}")


[[ 8  9 13 32 50]
 [ 5  1 96 68  8]
 [89 46 32 71 75]
 [70 50 27 24 37]
 [93 62 48 17 94]
 [81 93 86 60 70]
 [97 99 95 80  6]
 [29 76 42 14 44]
 [80 90 85 63 93]
 [87 59 58 74 68]]
{1: array([ 8,  9, 13, 32, 50]), 2: array([ 5,  1, 96, 68,  8]), 3: array([89, 46, 32, 71, 75]), 4: array([70, 50, 27, 24, 37]), 5: array([93, 62, 48, 17, 94]), 6: array([81, 93, 86, 60, 70]), 7: array([97, 99, 95, 80,  6]), 8: array([29, 76, 42, 14, 44]), 9: array([80, 90, 85, 63, 93]), 10: array([87, 59, 58, 74, 68])}
Course 1: [ 8  5 89 70 93 81 97 29 80 87]
Course 2: [ 9  1 46 50 62 93 99 76 90 59]
Course 3: [13 96 32 27 48 86 95 42 85 58]
Course 4: [32 68 71 24 17 60 80 14 63 74]
Course 5: [50  8 75 37 94 70  6 44 93 68]


In [22]:
#create two classes, student and course
# every course as an name,code
#every student has a name, regno
#then every student has several courses


class Courses:
    def __init__(self, name, code):
        self.name = name
        self.code = code

class Students:
    def __init__(self, name, regno):
        self.name = name
        self.regno = regno
        self.courses = []

    def register(self, course):
        self.courses.append(course)


course1 = Courses("ML","CSS203")
course2 = Courses("AI","CSS204")

student1 = Students("James","css/00057/022")
student1.register(course1)
student1.register(course2)


print(student1.name)
for course in student1.courses:
    print(f"The Course is {course.name} of unit code  ({course.code})")




James
The Course is ML of unit code  (CSS203)
The Course is AI of unit code  (CSS204)


In [32]:


vec1 = np.arange(6)
print(vec1)

[0 1 2 3 4 5]


In [46]:
from numpy import matrix

vec1 = np.arange(6)
res = matrix(vec1).tranpose()
print(res)

AttributeError: 'matrix' object has no attribute 'tranpose'