In [282]:
# CCS/00057/022 - James Wasonga
# CCS/03003/022 - Felix Awere

# Class Assignment

In [7]:
import numpy as np

v1 = np.arange(0,6)
print(v1)

v2 = [4,5,6,7]
mul = v1 * 2
print(mul)

add = mul*2
print(add)


[0 1 2 3 4 5]
[ 0  2  4  6  8 10]
[ 0  4  8 12 16 20]


In [9]:
# add2 = v1 + v2
# print(add2)

In [11]:
mat = v1.reshape(2,3)
print(mat)

[[0 1 2]
 [3 4 5]]


###### vec1 = np.arange(3)
print(vec1)
vec2 = np.arange(3)
# print(mat * vec1)
print(vec1 * mat)
# print(mat * vec2)


In [13]:
# creating three different matrices and maltiplying them 

v1 = np.arange(0,6)
mat1 = v1.reshape(2,3)

v2 = np.arange(0,9)
mat2 = v2.reshape(3,3)

v3 = np.arange(0,8)
mat3 = v3.reshape(2,4)

print(mat1)
print(mat2)
print(mat3)

# print(mat1 *mat2)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 3]
 [4 5 6 7]]


In [15]:
from numpy import matrix

# colvec = v1.transpose()
# print(colvec)

v3 = matrix(v1).transpose()
print(v3)

s = v3.shape
print(s)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [17]:
#converting the vector to matrix

hlp = np.arange(3)

v3 = matrix(hlp).transpose()
print(v3)
s = v3.shape
print(s)

# hlp.reshape(3,1)
# print(hlp)

[[0]
 [1]
 [2]]
(3, 1)


In [25]:
# multiplying 3*3 matrix and 3*1
print(mat1 * hlp)

[[ 0  1  4]
 [ 0  4 10]]


In [27]:
vec1 = np.arange(6)
res1 = vec1.reshape(2,3)
# print(res1)

vec2 = np.arange(2)
res2 = matrix(vec2).transpose()

print(res2 * res1)

ValueError: shapes (2,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [181]:
# difference between np.dot and direct multiplication of the vector

# print(res1 *res1)

np.dot(res1 ,res1)



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
# creating a square matrix to show wheher the dot product works

vec = np.arange(4)
val = vec.reshape(2,2)
# print(val)
res = np.dot(val ,val)
print(res)

[[ 2  3]
 [ 6 11]]


In [227]:
# dot multiplication of vectors

vec = np.arange(3)
# val = vec.reshape(2,3)
print(vec)

res = np.dot(vec,vec)
print(res)

[0 1 2]
5


In [239]:
vec = np.arange(6)
mat1 = vec.reshape(2,3)
print(mat1)

print(mat1.ravel()) # converting the reshaped matrix back to the normal
mat1.transpose().ravel() # it works the same as flatten


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


array([0, 3, 1, 4, 2, 5])

In [20]:
vec = np.arange(1,5)
val = vec.reshape(2,2)
print(val)

# np.repeat(val,2)
# np.tile(val,2)

np.concatenate((val,val), axis=1)

[[1 2]
 [3 4]]


array([[1, 2, 1, 2],
       [3, 4, 3, 4]])