In [ ]:
# CSS/00057/022 - JAMES WASONGA
# CSS/03003/022 - FELIX AWERE

# ASSIGNMENT3 SUBMISSION 

In [1]:
import numpy as np
import random

student_data = np.random.choice(np.arange(1,100), size=50).reshape(10,5)
print(student_data)

student = [1,2,3,4,5,6,7,8,9,10]
studentdict = {}
courses = [1,2,3,4,5]
marks = {}

for x in range(len(student_data)):
    studentdict.update({student[x]: student_data[x]})  
print(studentdict)

for i in range(student_data.shape[1]):
    print(f"Course {courses[i]}: {student_data[:, i]}")

[[78 80 88 96 95]
 [87 38  9 41 74]
 [42 62 98 44 14]
 [86 52 45 96 72]
 [35 33 13  3 30]
 [ 8 78  4 65 45]
 [89 44 55 38 49]
 [15 73 19 36 32]
 [ 8 60 71 81 82]
 [55 62 84  8 92]]
{1: array([78, 80, 88, 96, 95]), 2: array([87, 38,  9, 41, 74]), 3: array([42, 62, 98, 44, 14]), 4: array([86, 52, 45, 96, 72]), 5: array([35, 33, 13,  3, 30]), 6: array([ 8, 78,  4, 65, 45]), 7: array([89, 44, 55, 38, 49]), 8: array([15, 73, 19, 36, 32]), 9: array([ 8, 60, 71, 81, 82]), 10: array([55, 62, 84,  8, 92])}
Course 1: [78 87 42 86 35  8 89 15  8 55]
Course 2: [80 38 62 52 33 78 44 73 60 62]
Course 3: [88  9 98 45 13  4 55 19 71 84]
Course 4: [96 41 44 96  3 65 38 36 81  8]
Course 5: [95 74 14 72 30 45 49 32 82 92]


In [3]:
#create two classes, student and course
# every course as an name,code
#every student has a name, regno
#then every student has several courses


class Courses:
    def __init__(self, name, code):
        self.name = name
        self.code = code

class Students:
    def __init__(self, name, regno):
        self.name = name
        self.regno = regno
        self.courses = []

    def register(self, course):
        self.courses.append(course)


course1 = Courses("ML","CSS203")
course2 = Courses("AI","CSS204")

student1 = Students("James","css/00057/022")
student1.register(course1)
student1.register(course2)


print(student1.name)
for course in student1.courses:
    print(f"The Course is {course.name} of unit code  ({course.code})")




James
The Course is ML of unit code  (CSS203)
The Course is AI of unit code  (CSS204)
