In [ ]:
# CCS/00057/022 - JAMES WASONGA
# CCS/03003/022 - FELIX AWERE

# ASSIGNMENT2 SUBMISSION 

In [15]:



#total marks for each students
#mean marks for each subject 
#computing graduation unit for each student best four

import numpy as np
import random

student_data = np.random.choice(np.arange(20,100),size = 50).reshape(10,5)
student_ids = [1,2,3,4,5,6,7,8,9,10]
for i in range(len(student_data)):
    print(student_ids[i], student_data[i])

#total marks for each students
total_marks = np.sum(student_data, axis=1)
# print(total_marks)

#mean marks for students
mean_marks = np.mean(student_data, axis=0)
# print(mean_marks)

#computing graduation unit for each student best four
graduation_unit =  np.sort(student_data, axis=1)[:, -4:]
print(f"The graduation uint : {graduation_unit}")

sum_of_units = np.sum(graduation_unit, axis =1)
print(sum_of_units)

for i, s, w in zip(student_ids, graduation_unit, sum_of_units):
    print(f" Student {i} has best {s} unit with total of {w}")

    


1 [52 47 35 22 71]
2 [50 87 31 34 81]
3 [26 49 95 77 85]
4 [41 36 31 22 25]
5 [66 49 30 29 35]
6 [48 22 59 55 95]
7 [93 25 98 25 92]
8 [32 40 91 52 92]
9 [52 74 50 41 41]
10 [73 58 75 66 52]
The graduation uint : [[35 47 52 71]
 [34 50 81 87]
 [49 77 85 95]
 [25 31 36 41]
 [30 35 49 66]
 [48 55 59 95]
 [25 92 93 98]
 [40 52 91 92]
 [41 50 52 74]
 [58 66 73 75]]
[205 252 306 133 180 257 308 275 217 272]
 Student 1 has best [35 47 52 71] unit with total of 205
 Student 2 has best [34 50 81 87] unit with total of 252
 Student 3 has best [49 77 85 95] unit with total of 306
 Student 4 has best [25 31 36 41] unit with total of 133
 Student 5 has best [30 35 49 66] unit with total of 180
 Student 6 has best [48 55 59 95] unit with total of 257
 Student 7 has best [25 92 93 98] unit with total of 308
 Student 8 has best [40 52 91 92] unit with total of 275
 Student 9 has best [41 50 52 74] unit with total of 217
 Student 10 has best [58 66 73 75] unit with total of 272
