In [42]:
import numpy as np


In [8]:
a = np.arange(10).reshape(2,5)
b = np.arange(20).reshape(5,4)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [28]:
v = np.array([1,2,3,4])
print(v)
v = np.arange(1,5).reshape(1,4)
print(v[0][1])
print(type(v))
print(v.size)
print(v.ndim)


[1 2 3 4]
2
<class 'numpy.ndarray'>
4
2


In [30]:
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [32]:
np.linspace?


Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000026D1ECDFB00>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end v

In [34]:
m = np.random.rand(5,5)
print(m)

[[0.74371036 0.98509499 0.56851743 0.06697386 0.44238371]
 [0.56050068 0.6478368  0.84971676 0.26728395 0.20444676]
 [0.48806569 0.37451631 0.91341525 0.88508405 0.33490033]
 [0.91420082 0.19356217 0.8949876  0.57421319 0.81877988]
 [0.33640452 0.78695404 0.49563451 0.77916887 0.81421554]]


In [36]:
m = np.random.randn(5,5)
print(m)

[[-1.8477436  -0.36172007  0.00612785 -2.96851683  0.50230228]
 [-0.98310764 -0.60851048 -0.87969503  0.52589668 -0.01008543]
 [-1.92580743  0.40700906 -0.94068931 -0.24143075 -0.09809488]
 [ 1.48189285 -1.00215155 -0.18379796 -0.33203218 -0.62661991]
 [ 0.63999514  0.4726571  -0.59163248 -0.32374516 -0.36250512]]


In [50]:
m = np.ones((3,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
m = np.empty((2,3))
print(m)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22647253e-307 2.67018777e-306 2.42092166e-322]]


In [67]:
m = np.arange(5)
print(m)

[0 1 2 3 4]


In [84]:
k = np.array([1,2.,3])
k.dtype

dtype('float64')

In [105]:
M = np.random.rand(10, 2)
print(M[0])


[0.71695665 0.44043665]


In [111]:
z = np.arange(0,5)
z * 2 


array([0, 2, 4, 6, 8])

In [ ]:
# determine if a function is divisible by two and return a remainder